// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3CkEH-CR06PGQjLLn1j4ToMW0GCgPQyw',
    appId: '1:545699711471:web:ced3d9813516ab4fab8e1a',
    messagingSenderId: '545699711471',
    projectId: 'fooddeliverylosrepas',
    authDomain: 'fooddeliverylosrepas.firebaseapp.com',
    storageBucket: 'fooddeliverylosrepas.firebasestorage.app',
    measurementId: 'G-K3KH50B8HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdvo-s-UO9ndKFW2Po1Yu30jYdTF3s4w',
    appId: '1:545699711471:android:30c7e6578d96b61bab8e1a',
    messagingSenderId: '545699711471',
    projectId: 'fooddeliverylosrepas',
    storageBucket: 'fooddeliverylosrepas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm1QX_VErBoTefB6Ui1RXejDFQ0r2zt8w',
    appId: '1:545699711471:ios:2af6d69c952b11c2ab8e1a',
    messagingSenderId: '545699711471',
    projectId: 'fooddeliverylosrepas',
    storageBucket: 'fooddeliverylosrepas.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAppJesusKuMarcoVelasco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm1QX_VErBoTefB6Ui1RXejDFQ0r2zt8w',
    appId: '1:545699711471:ios:2af6d69c952b11c2ab8e1a',
    messagingSenderId: '545699711471',
    projectId: 'fooddeliverylosrepas',
    storageBucket: 'fooddeliverylosrepas.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAppJesusKuMarcoVelasco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3CkEH-CR06PGQjLLn1j4ToMW0GCgPQyw',
    appId: '1:545699711471:web:3a7803a07f8232a4ab8e1a',
    messagingSenderId: '545699711471',
    projectId: 'fooddeliverylosrepas',
    authDomain: 'fooddeliverylosrepas.firebaseapp.com',
    storageBucket: 'fooddeliverylosrepas.firebasestorage.app',
    measurementId: 'G-G9RD7C70K0',
  );
}
